// Code generated by scene-script-cli. DO NOT EDIT.

package script_task

import (
	"github.com/gin-gonic/gin"

	"scene-script/internal/logic/script_task"
	"scene-script/internal/svc"
	"scene-script/internal/types"
	"scene-script/pkg/httpn"
)

// CreateScriptTaskHandler 创建
func CreateScriptTaskHandler(svc *svc.ServiceContext) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req types.CreateScriptTaskReq
		if err := httpn.BindJSON(c, &req); err != nil {
			httpn.Error(c, err)
			return
		}

		l := script_task.NewCreateScriptTaskLogic(c.Request.Context(), svc)
		resp, err := l.CreateScriptTask(&req)
		if err != nil {
			httpn.HandleError(c, err)
			return
		}

		httpn.Ok(c, resp)
	}
}
