// Code generated by scene-script-cli. DO NOT EDIT.

package script_task

import (
	"github.com/gin-gonic/gin"

	"scene-script/internal/logic/script_task"
	"scene-script/internal/svc"
	"scene-script/pkg/httpn"
)

// GetScriptTaskHandler 获取
func GetScriptTaskHandler(svc *svc.ServiceContext) gin.HandlerFunc {
	return func(c *gin.Context) {
		id, err := httpn.PathInt64(c, "id")
		if err != nil {
			httpn.BadRequest(c, "无效的ID")
			return
		}

		l := script_task.NewGetScriptTaskLogic(c.Request.Context(), svc)
		resp, err := l.GetScriptTask(id)
		if err != nil {
			httpn.HandleError(c, err)
			return
		}

		httpn.Ok(c, resp)
	}
}
