// Code generated by scene-script-cli. DO NOT EDIT.

package script_task

import (
	"github.com/gin-gonic/gin"

	"scene-script/internal/logic/script_task"
	"scene-script/internal/svc"
	"scene-script/internal/types"
	"scene-script/pkg/httpn"
)

// UpdateScriptTaskHandler 更新
func UpdateScriptTaskHandler(svc *svc.ServiceContext) gin.HandlerFunc {
	return func(c *gin.Context) {
		id, err := httpn.PathInt64(c, "id")
		if err != nil {
			httpn.BadRequest(c, "无效的ID")
			return
		}

		var req types.UpdateScriptTaskReq
		if err := httpn.BindJSON(c, &req); err != nil {
			httpn.Error(c, err)
			return
		}
		req.ID = id

		l := script_task.NewUpdateScriptTaskLogic(c.Request.Context(), svc)
		resp, err := l.UpdateScriptTask(&req)
		if err != nil {
			httpn.HandleError(c, err)
			return
		}

		httpn.Ok(c, resp)
	}
}
