// Code generated by scene-script-cli. DO NOT EDIT.

package types

import "time"

// CreateScriptTaskReq 创建请求
type CreateScriptTaskReq struct {
	TaskID         string `json:"task_id" validate:"required,max=64"`
	UserID         int64  `json:"user_id"`
	Title          string `json:"title" validate:"max=255"`
	Genre          string `json:"genre" validate:"max=64"`
	Tone           string `json:"tone" validate:"max=64"`
	Pacing         string `json:"pacing" validate:"required"`
	SourceChapters int    `json:"source_chapters" validate:"required"`
	Status         string `json:"status" validate:"required"`
	ErrMsg         string `json:"err_msg"`
}

// UpdateScriptTaskReq 更新请求
type UpdateScriptTaskReq struct {
	ID             int64  `json:"id"`
	TaskID         string `json:"task_id" validate:"omitempty"`
	UserID         int64  `json:"user_id" validate:"omitempty"`
	Title          string `json:"title" validate:"omitempty"`
	Genre          string `json:"genre" validate:"omitempty"`
	Tone           string `json:"tone" validate:"omitempty"`
	Pacing         string `json:"pacing" validate:"omitempty"`
	SourceChapters int    `json:"source_chapters" validate:"omitempty"`
	Status         string `json:"status" validate:"omitempty"`
	ErrMsg         string `json:"err_msg" validate:"omitempty"`
}

// ScriptTaskResp 响应
type ScriptTaskResp struct {
	ID             int64     `json:"id"`
	TaskID         string    `json:"task_id"`
	UserID         int64     `json:"user_id"`
	Title          string    `json:"title"`
	Genre          string    `json:"genre"`
	Tone           string    `json:"tone"`
	Pacing         string    `json:"pacing"`
	SourceChapters int       `json:"source_chapters"`
	Status         string    `json:"status"`
	ErrMsg         string    `json:"err_msg"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
