// Code generated by scene-script-cli. DO NOT EDIT.

package types

import "time"

// CreateScriptChapterReq 创建请求
type CreateScriptChapterReq struct {
	TaskID       string `json:"task_id" validate:"required,max=64"`
	ChapterIndex int    `json:"chapter_index" validate:"required"`
	ChapterTitle string `json:"chapter_title" validate:"max=255"`
	ChapterText  string `json:"chapter_text" validate:"required"`
}

// UpdateScriptChapterReq 更新请求
type UpdateScriptChapterReq struct {
	ID           int64  `json:"id"`
	TaskID       string `json:"task_id" validate:"omitempty"`
	ChapterIndex int    `json:"chapter_index" validate:"omitempty"`
	ChapterTitle string `json:"chapter_title" validate:"omitempty"`
	ChapterText  string `json:"chapter_text" validate:"omitempty"`
}

// ScriptChapterResp 响应
type ScriptChapterResp struct {
	ID           int64     `json:"id"`
	TaskID       string    `json:"task_id"`
	ChapterIndex int       `json:"chapter_index"`
	ChapterTitle string    `json:"chapter_title"`
	ChapterText  string    `json:"chapter_text"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
