package codegen

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"scene-script/cmd/cli/internal/parser"
)

// CodeGenerator 代码生成器
type CodeGenerator struct {
	tables []parser.TableDef
}

// NewCodeGenerator 创建代码生成器
func NewCodeGenerator(tables []parser.TableDef) *CodeGenerator {
	return &CodeGenerator{
		tables: tables,
	}
}

// GenerateTypes 生成 Types 代码
func (g *CodeGenerator) GenerateTypes() map[string]string {
	files := make(map[string]string)

	for _, table := range g.tables {
		moduleName := toModuleName(table.Name)
		content := g.generateTypesForTable(table, moduleName)
		files[moduleName+".go"] = content
	}

	return files
}

// generateTypesForTable 为单个表生成 Types
func (g *CodeGenerator) generateTypesForTable(table parser.TableDef, moduleName string) string {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by scene-script-cli. DO NOT EDIT.\n\n")
	buf.WriteString("package types\n\n")

	// 检测是否需要导入 time 包
	needsTimeImport := false
	for _, col := range table.Columns {
		if col.GoType == "time.Time" {
			needsTimeImport = true
			break
		}
	}

	if needsTimeImport {
		buf.WriteString("import \"time\"\n\n")
	}

	entityName := parser.ToCamelCase(moduleName) // 使用模块名（单数）

	// 生成 Create Request
	buf.WriteString(fmt.Sprintf("// Create%sReq 创建%s请求\n", entityName, table.Comment))
	buf.WriteString(fmt.Sprintf("type Create%sReq struct {\n", entityName))
	for _, col := range table.Columns {
		if col.IsPrimaryKey || col.IsAutoIncr || col.Name == "created_at" || col.Name == "updated_at" {
			continue
		}
		buf.WriteString(fmt.Sprintf("\t%s %s", parser.ToCamelCase(col.Name), col.GoType))
		tags := fmt.Sprintf(" `json:\"%s\"", col.JSONTag)
		if col.ValidateTag != "" {
			tags += fmt.Sprintf(" validate:\"%s\"", col.ValidateTag)
		}
		tags += "`"
		buf.WriteString(tags)
		if col.Comment != "" {
			buf.WriteString(fmt.Sprintf(" // %s", col.Comment))
		}
		buf.WriteString("\n")
	}
	buf.WriteString("}\n\n")

	// 生成 Update Request
	buf.WriteString(fmt.Sprintf("// Update%sReq 更新%s请求\n", entityName, table.Comment))
	buf.WriteString(fmt.Sprintf("type Update%sReq struct {\n", entityName))

	// 先添加 ID 字段（用于路径参数）
	for _, col := range table.Columns {
		if col.IsPrimaryKey {
			buf.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`", parser.ToCamelCase(col.Name), col.GoType, col.JSONTag))
			if col.Comment != "" {
				buf.WriteString(fmt.Sprintf(" // %s", col.Comment))
			}
			buf.WriteString("\n")
			break
		}
	}

	// 再添加其他可更新字段
	for _, col := range table.Columns {
		if col.IsPrimaryKey || col.IsAutoIncr || col.Name == "created_at" || col.Name == "updated_at" {
			continue
		}
		buf.WriteString(fmt.Sprintf("\t%s %s", parser.ToCamelCase(col.Name), col.GoType))
		tags := fmt.Sprintf(" `json:\"%s\" validate:\"omitempty\"`", col.JSONTag)
		buf.WriteString(tags)
		if col.Comment != "" {
			buf.WriteString(fmt.Sprintf(" // %s", col.Comment))
		}
		buf.WriteString("\n")
	}
	buf.WriteString("}\n\n")

	// 生成 Response
	buf.WriteString(fmt.Sprintf("// %sResp %s响应\n", entityName, table.Comment))
	buf.WriteString(fmt.Sprintf("type %sResp struct {\n", entityName))
	for _, col := range table.Columns {
		if col.Name == "password" {
			continue
		}
		buf.WriteString(fmt.Sprintf("\t%s %s", parser.ToCamelCase(col.Name), col.GoType))
		tags := fmt.Sprintf(" `json:\"%s\"`", col.JSONTag)
		buf.WriteString(tags)
		if col.Comment != "" {
			buf.WriteString(fmt.Sprintf(" // %s", col.Comment))
		}
		buf.WriteString("\n")
	}
	buf.WriteString("}\n")

	return buf.String()
}

// GenerateHandlers 生成 Handler 代码
func (g *CodeGenerator) GenerateHandlers() map[string]string {
	files := make(map[string]string)

	for _, table := range g.tables {
		moduleName := toModuleName(table.Name)

		// 生成 CRUD handlers
		files[fmt.Sprintf("create_%s_handler.go", moduleName)] = g.generateCreateHandler(table, moduleName)
		files[fmt.Sprintf("get_%s_handler.go", moduleName)] = g.generateGetHandler(table, moduleName)
		files[fmt.Sprintf("update_%s_handler.go", moduleName)] = g.generateUpdateHandler(table, moduleName)
		files[fmt.Sprintf("delete_%s_handler.go", moduleName)] = g.generateDeleteHandler(table, moduleName)
	}

	return files
}

// generateCreateHandler 生成创建 Handler
func (g *CodeGenerator) generateCreateHandler(table parser.TableDef, moduleName string) string {
	entityName := parser.ToCamelCase(moduleName) // 使用模块名（单数）

	tmpl := `// Code generated by scene-script-cli. DO NOT EDIT.

package {{.ModuleName}}

import (
	"github.com/gin-gonic/gin"

	"scene-script/internal/logic/{{.ModuleName}}"
	"scene-script/internal/svc"
	"scene-script/internal/types"
	"scene-script/pkg/httpn"
)

// Create{{.EntityName}}Handler 创建{{.Comment}}
func Create{{.EntityName}}Handler(svc *svc.ServiceContext) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req types.Create{{.EntityName}}Req
		if err := httpn.BindJSON(c, &req); err != nil {
			httpn.Error(c, err)
			return
		}

		l := {{.ModuleName}}.NewCreate{{.EntityName}}Logic(c.Request.Context(), svc)
		resp, err := l.Create{{.EntityName}}(&req)
		if err != nil {
			httpn.HandleError(c, err)
			return
		}

		httpn.Ok(c, resp)
	}
}
`

	t := template.Must(template.New("handler").Parse(tmpl))
	var buf bytes.Buffer
	t.Execute(&buf, map[string]string{
		"ModuleName": moduleName,
		"EntityName": entityName,
		"Comment":    table.Comment,
	})

	return buf.String()
}

// generateGetHandler 生成获取 Handler
func (g *CodeGenerator) generateGetHandler(table parser.TableDef, moduleName string) string {
	entityName := parser.ToCamelCase(moduleName) // 使用模块名（单数）

	tmpl := `// Code generated by scene-script-cli. DO NOT EDIT.

package {{.ModuleName}}

import (
	"github.com/gin-gonic/gin"

	"scene-script/internal/logic/{{.ModuleName}}"
	"scene-script/internal/svc"
	"scene-script/pkg/httpn"
)

// Get{{.EntityName}}Handler 获取{{.Comment}}
func Get{{.EntityName}}Handler(svc *svc.ServiceContext) gin.HandlerFunc {
	return func(c *gin.Context) {
		id, err := httpn.PathInt64(c, "id")
		if err != nil {
			httpn.BadRequest(c, "无效的ID")
			return
		}

		l := {{.ModuleName}}.NewGet{{.EntityName}}Logic(c.Request.Context(), svc)
		resp, err := l.Get{{.EntityName}}(id)
		if err != nil {
			httpn.HandleError(c, err)
			return
		}

		httpn.Ok(c, resp)
	}
}
`

	t := template.Must(template.New("handler").Parse(tmpl))
	var buf bytes.Buffer
	t.Execute(&buf, map[string]string{
		"ModuleName": moduleName,
		"EntityName": entityName,
		"Comment":    table.Comment,
	})

	return buf.String()
}

// generateUpdateHandler 生成更新 Handler
func (g *CodeGenerator) generateUpdateHandler(table parser.TableDef, moduleName string) string {
	entityName := parser.ToCamelCase(moduleName) // 使用模块名（单数）

	tmpl := `// Code generated by scene-script-cli. DO NOT EDIT.

package {{.ModuleName}}

import (
	"github.com/gin-gonic/gin"

	"scene-script/internal/logic/{{.ModuleName}}"
	"scene-script/internal/svc"
	"scene-script/internal/types"
	"scene-script/pkg/httpn"
)

// Update{{.EntityName}}Handler 更新{{.Comment}}
func Update{{.EntityName}}Handler(svc *svc.ServiceContext) gin.HandlerFunc {
	return func(c *gin.Context) {
		id, err := httpn.PathInt64(c, "id")
		if err != nil {
			httpn.BadRequest(c, "无效的ID")
			return
		}

		var req types.Update{{.EntityName}}Req
		if err := httpn.BindJSON(c, &req); err != nil {
			httpn.Error(c, err)
			return
		}
		req.ID = id

		l := {{.ModuleName}}.NewUpdate{{.EntityName}}Logic(c.Request.Context(), svc)
		resp, err := l.Update{{.EntityName}}(&req)
		if err != nil {
			httpn.HandleError(c, err)
			return
		}

		httpn.Ok(c, resp)
	}
}
`

	t := template.Must(template.New("handler").Parse(tmpl))
	var buf bytes.Buffer
	t.Execute(&buf, map[string]string{
		"ModuleName": moduleName,
		"EntityName": entityName,
		"Comment":    table.Comment,
	})

	return buf.String()
}

// generateDeleteHandler 生成删除 Handler
func (g *CodeGenerator) generateDeleteHandler(table parser.TableDef, moduleName string) string {
	entityName := parser.ToCamelCase(moduleName) // 使用模块名（单数）

	tmpl := `// Code generated by scene-script-cli. DO NOT EDIT.

package {{.ModuleName}}

import (
	"github.com/gin-gonic/gin"

	"scene-script/internal/logic/{{.ModuleName}}"
	"scene-script/internal/svc"
	"scene-script/pkg/httpn"
)

// Delete{{.EntityName}}Handler 删除{{.Comment}}
func Delete{{.EntityName}}Handler(svc *svc.ServiceContext) gin.HandlerFunc {
	return func(c *gin.Context) {
		id, err := httpn.PathInt64(c, "id")
		if err != nil {
			httpn.BadRequest(c, "无效的ID")
			return
		}

		l := {{.ModuleName}}.NewDelete{{.EntityName}}Logic(c.Request.Context(), svc)
		err = l.Delete{{.EntityName}}(id)
		if err != nil {
			httpn.HandleError(c, err)
			return
		}

		httpn.Ok(c, nil)
	}
}
`

	t := template.Must(template.New("handler").Parse(tmpl))
	var buf bytes.Buffer
	t.Execute(&buf, map[string]string{
		"ModuleName": moduleName,
		"EntityName": entityName,
		"Comment":    table.Comment,
	})

	return buf.String()
}

// GenerateLogics 生成 Logic 代码
func (g *CodeGenerator) GenerateLogics() map[string]string {
	files := make(map[string]string)

	for _, table := range g.tables {
		moduleName := toModuleName(table.Name)

		// 生成 CRUD logics
		files[fmt.Sprintf("create_%s_logic.go", moduleName)] = g.generateCreateLogic(table, moduleName)
		files[fmt.Sprintf("get_%s_logic.go", moduleName)] = g.generateGetLogic(table, moduleName)
		files[fmt.Sprintf("update_%s_logic.go", moduleName)] = g.generateUpdateLogic(table, moduleName)
		files[fmt.Sprintf("delete_%s_logic.go", moduleName)] = g.generateDeleteLogic(table, moduleName)
	}

	return files
}

// generateCreateLogic 生成创建 Logic
func (g *CodeGenerator) generateCreateLogic(table parser.TableDef, moduleName string) string {
	entityName := parser.ToCamelCase(moduleName) // 使用模块名（单数）

	tmpl := `package {{.ModuleName}}

import (
	"context"

	"go.uber.org/zap"

	"scene-script/internal/svc"
	"scene-script/internal/types"
	"scene-script/pkg/errorn"
	"scene-script/pkg/logn"
)

type Create{{.EntityName}}Logic struct {
	*logn.Logger
	c   context.Context
	svc *svc.ServiceContext
}

func NewCreate{{.EntityName}}Logic(c context.Context, svc *svc.ServiceContext) *Create{{.EntityName}}Logic {
	return &Create{{.EntityName}}Logic{
		c:      c,
		svc:    svc,
		Logger: logn.WithContext(c),
	}
}

func (l *Create{{.EntityName}}Logic) Create{{.EntityName}}(req *types.Create{{.EntityName}}Req) (*types.{{.EntityName}}Resp, error) {
	// TODO: 实现创建逻辑
	l.Info("Creating {{.ModuleName}}", zap.Any("req", req))
	
	return nil, errorn.NewDefault("Not implemented")
}
`

	t := template.Must(template.New("logic").Parse(tmpl))
	var buf bytes.Buffer
	t.Execute(&buf, map[string]string{
		"ModuleName": moduleName,
		"EntityName": entityName,
	})

	return buf.String()
}

// generateGetLogic 生成获取 Logic
func (g *CodeGenerator) generateGetLogic(table parser.TableDef, moduleName string) string {
	entityName := parser.ToCamelCase(moduleName) // 使用模块名（单数）

	tmpl := `package {{.ModuleName}}

import (
	"context"

	"go.uber.org/zap"

	"scene-script/internal/svc"
	"scene-script/internal/types"
	"scene-script/pkg/errorn"
	"scene-script/pkg/logn"
)

type Get{{.EntityName}}Logic struct {
	*logn.Logger
	c   context.Context
	svc *svc.ServiceContext
}

func NewGet{{.EntityName}}Logic(c context.Context, svc *svc.ServiceContext) *Get{{.EntityName}}Logic {
	return &Get{{.EntityName}}Logic{
		c:      c,
		svc:    svc,
		Logger: logn.WithContext(c),
	}
}

func (l *Get{{.EntityName}}Logic) Get{{.EntityName}}(id int64) (*types.{{.EntityName}}Resp, error) {
	// TODO: 实现获取逻辑
	l.Info("Getting {{.ModuleName}}", zap.Int64("id", id))
	
	return nil, errorn.NewDefault("Not implemented")
}
`

	t := template.Must(template.New("logic").Parse(tmpl))
	var buf bytes.Buffer
	t.Execute(&buf, map[string]string{
		"ModuleName": moduleName,
		"EntityName": entityName,
	})

	return buf.String()
}

// generateUpdateLogic 生成更新 Logic
func (g *CodeGenerator) generateUpdateLogic(table parser.TableDef, moduleName string) string {
	entityName := parser.ToCamelCase(moduleName) // 使用模块名（单数）

	tmpl := `package {{.ModuleName}}

import (
	"context"

	"go.uber.org/zap"

	"scene-script/internal/svc"
	"scene-script/internal/types"
	"scene-script/pkg/errorn"
	"scene-script/pkg/logn"
)

type Update{{.EntityName}}Logic struct {
	*logn.Logger
	c   context.Context
	svc *svc.ServiceContext
}

func NewUpdate{{.EntityName}}Logic(c context.Context, svc *svc.ServiceContext) *Update{{.EntityName}}Logic {
	return &Update{{.EntityName}}Logic{
		c:      c,
		svc:    svc,
		Logger: logn.WithContext(c),
	}
}

func (l *Update{{.EntityName}}Logic) Update{{.EntityName}}(req *types.Update{{.EntityName}}Req) (*types.{{.EntityName}}Resp, error) {
	// TODO: 实现更新逻辑
	l.Info("Updating {{.ModuleName}}", zap.Any("req", req))
	
	return nil, errorn.NewDefault("Not implemented")
}
`

	t := template.Must(template.New("logic").Parse(tmpl))
	var buf bytes.Buffer
	t.Execute(&buf, map[string]string{
		"ModuleName": moduleName,
		"EntityName": entityName,
	})

	return buf.String()
}

// generateDeleteLogic 生成删除 Logic
func (g *CodeGenerator) generateDeleteLogic(table parser.TableDef, moduleName string) string {
	entityName := parser.ToCamelCase(moduleName) // 使用模块名（单数）

	tmpl := `package {{.ModuleName}}

import (
	"context"

	"go.uber.org/zap"

	"scene-script/internal/svc"
	"scene-script/pkg/errorn"
	"scene-script/pkg/logn"
)

type Delete{{.EntityName}}Logic struct {
	*logn.Logger
	c   context.Context
	svc *svc.ServiceContext
}

func NewDelete{{.EntityName}}Logic(c context.Context, svc *svc.ServiceContext) *Delete{{.EntityName}}Logic {
	return &Delete{{.EntityName}}Logic{
		c:      c,
		svc:    svc,
		Logger: logn.WithContext(c),
	}
}

func (l *Delete{{.EntityName}}Logic) Delete{{.EntityName}}(id int64) error {
	// TODO: 实现删除逻辑
	l.Info("Deleting {{.ModuleName}}", zap.Int64("id", id))
	
	return errorn.NewDefault("Not implemented")
}
`

	t := template.Must(template.New("logic").Parse(tmpl))
	var buf bytes.Buffer
	t.Execute(&buf, map[string]string{
		"ModuleName": moduleName,
		"EntityName": entityName,
	})

	return buf.String()
}

// GenerateModels 生成 Model 代码
func (g *CodeGenerator) GenerateModels() map[string]string {
	files := make(map[string]string)

	for _, table := range g.tables {
		moduleName := toModuleName(table.Name)
		content := g.generateModelForTable(table, moduleName)
		files[moduleName+".go"] = content
	}

	return files
}

// generateModelForTable 为单个表生成 Model
func (g *CodeGenerator) generateModelForTable(table parser.TableDef, moduleName string) string {
	entityName := parser.ToCamelCase(moduleName)

	// 获取主键字段
	var pkField parser.ColumnDef
	for _, col := range table.Columns {
		if col.IsPrimaryKey {
			pkField = col
			break
		}
	}

	tmpl := `package model

import (
	"context"
	"database/sql"
	"time"

	"scene-script/pkg/stores/sqlx"
)

var (
	{{.LowerEntityName}}FieldNames        = "{{.SelectFields}}"
	{{.LowerEntityName}}RowsExpectAutoSet = "{{.InsertFields}}"
)

type {{.EntityName}} struct {
{{range .Columns}}	{{.FieldName}} {{.GoType}} ` + "`db:\"{{.DBTag}}\" json:\"{{.JSONTag}}\"`" + `{{if .Comment}} // {{.Comment}}{{end}}
{{end}}}

type {{.EntityName}}Model interface {
	{{.LowerEntityName}}Model
	// BEGIN: customizable methods (preserved during code regeneration)
	// Add your custom methods here
	// END: customizable methods
}

type {{.LowerEntityName}}Model interface {
	Insert(ctx context.Context, data *{{.EntityName}}) (int64, error)
	FindOne(ctx context.Context, id {{.PKType}}) (*{{.EntityName}}, error)
	Update(ctx context.Context, data *{{.EntityName}}) error
	Delete(ctx context.Context, id {{.PKType}}) error
	Trans(ctx context.Context, fn func(context.Context, {{.EntityName}}Model) error) error
}

type default{{.EntityName}}Model struct {
	conn  sqlx.SqlConn
	table string
}

func New{{.EntityName}}Model(conn sqlx.SqlConn) {{.EntityName}}Model {
	return &default{{.EntityName}}Model{
		conn:  conn,
		table: "{{.TableName}}",
	}
}

func (m *default{{.EntityName}}Model) Insert(ctx context.Context, data *{{.EntityName}}) (int64, error) {
	query := ` + "`INSERT INTO `" + ` + m.table + ` + "` ({{.InsertFields}}) VALUES ({{.InsertPlaceholders}})`" + `
	
	result, err := m.conn.ExecCtx(ctx, query, {{.InsertValues}})
	if err != nil {
		return 0, err
	}
	
	return result.LastInsertId()
}

func (m *default{{.EntityName}}Model) FindOne(ctx context.Context, id {{.PKType}}) (*{{.EntityName}}, error) {
	query := ` + "`SELECT `" + ` + {{.LowerEntityName}}FieldNames + ` + "` FROM `" + ` + m.table + ` + "` WHERE {{.PKColumn}} = ?`" + `
	
	var data {{.EntityName}}
	err := m.conn.QueryRowCtx(ctx, &data, query, id)
	
	switch err {
	case nil:
		return &data, nil
	case sql.ErrNoRows:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *default{{.EntityName}}Model) Update(ctx context.Context, data *{{.EntityName}}) error {
	query := ` + "`UPDATE `" + ` + m.table + ` + "` SET {{.UpdateFields}} WHERE {{.PKColumn}} = ?`" + `
	
	_, err := m.conn.ExecCtx(ctx, query, {{.UpdateValues}})
	return err
}

func (m *default{{.EntityName}}Model) Delete(ctx context.Context, id {{.PKType}}) error {
	query := ` + "`DELETE FROM `" + ` + m.table + ` + "` WHERE {{.PKColumn}} = ?`" + `
	
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *default{{.EntityName}}Model) Trans(ctx context.Context, fn func(context.Context, {{.EntityName}}Model) error) error {
	return m.conn.TransactCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) error {
		transModel := &default{{.EntityName}}Model{
			conn:  conn,
			table: m.table,
		}
		return fn(ctx, transModel)
	})
}
`

	type ModelColumn struct {
		FieldName string
		GoType    string
		DBTag     string
		JSONTag   string
		Comment   string
	}

	var columns []ModelColumn
	for _, col := range table.Columns {
		columns = append(columns, ModelColumn{
			FieldName: parser.ToCamelCase(col.Name),
			GoType:    col.GoType,
			DBTag:     col.Name,
			JSONTag:   col.JSONTag,
			Comment:   col.Comment,
		})
	}

	// 构建字段列表
	var insertFields, insertPlaceholders, insertValues []string
	var updateFields, updateValues []string
	var selectFields []string

	for _, col := range table.Columns {
		selectFields = append(selectFields, col.Name)

		if col.IsPrimaryKey || col.IsAutoIncr || col.Name == "created_at" || col.Name == "updated_at" {
			continue
		}

		insertFields = append(insertFields, col.Name)
		insertPlaceholders = append(insertPlaceholders, "?")
		insertValues = append(insertValues, "data."+parser.ToCamelCase(col.Name))

		updateFields = append(updateFields, col.Name+" = ?")
		updateValues = append(updateValues, "data."+parser.ToCamelCase(col.Name))
	}

	// 添加时间字段
	insertFields = append(insertFields, "created_at", "updated_at")
	insertPlaceholders = append(insertPlaceholders, "?", "?")
	insertValues = append(insertValues, "time.Now()", "time.Now()")

	updateFields = append(updateFields, "updated_at = ?")
	updateValues = append(updateValues, "time.Now()")
	updateValues = append(updateValues, "data."+parser.ToCamelCase(pkField.Name))

	data := map[string]interface{}{
		"EntityName":         entityName,
		"LowerEntityName":    toLowerFirst(entityName),
		"TableName":          table.Name,
		"Columns":            columns,
		"PKColumn":           pkField.Name,
		"PKType":             pkField.GoType,
		"InsertFields":       strings.Join(insertFields, ", "),
		"InsertPlaceholders": strings.Join(insertPlaceholders, ", "),
		"InsertValues":       strings.Join(insertValues, ", "),
		"SelectFields":       strings.Join(selectFields, ", "),
		"UpdateFields":       strings.Join(updateFields, ", "),
		"UpdateValues":       strings.Join(updateValues, ", "),
	}

	t := template.Must(template.New("model").Parse(tmpl))
	var buf bytes.Buffer
	t.Execute(&buf, data)

	return buf.String()
}

// toModuleName 转换为模块名（单数形式，去除前缀）
func toModuleName(tableName string) string {
	if tableName == "" {
		return ""
	}

	name := tableName

	// 去除常见表前缀
	prefixes := []string{"sys_", "t_", "tb_", "tbl_"}
	for _, prefix := range prefixes {
		if strings.HasPrefix(name, prefix) {
			name = strings.TrimPrefix(name, prefix)
			break
		}
	}

	// 去除复数后缀 s（如果是下划线分隔的，只处理最后一部分）
	// sys_user -> user (已去除前缀)
	// users -> user
	if strings.HasSuffix(name, "s") && !strings.HasSuffix(name, "ss") {
		name = strings.TrimSuffix(name, "s")
	}

	return name
}

// toLowerFirst 将首字母转换为小写
func toLowerFirst(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToLower(s[:1]) + s[1:]
}
