package astutil

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

// CodeMarker 代码生成标记
const (
	GeneratedMarker       = "// Code generated by scene-script-cli. DO NOT EDIT."
	LegacyGeneratedMarker = "// Code generated by scene-script-cli. DO NOT EDIT."
	ManualMarker          = "// Manual code below - preserved during regeneration"
)

// MergeResult 合并结果
type MergeResult struct {
	Content  string
	Modified bool
	Action   string // "created", "updated", "unchanged"
}

// MergeFile 智能合并文件
// 如果文件不存在，直接创建
// 如果文件存在且有生成标记，替换生成部分，保留手动部分
// 如果文件存在但无生成标记，不覆盖（手动文件）
func MergeFile(filePath string, newContent string) (*MergeResult, error) {
	// 检查文件是否存在
	existingContent, err := os.ReadFile(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			// 文件不存在，直接创建
			return &MergeResult{
				Content:  newContent,
				Modified: true,
				Action:   "created",
			}, nil
		}
		return nil, err
	}

	contentStr := string(existingContent)

	// 检查现有文件是否有生成标记（兼容旧版标记）
	if !strings.Contains(contentStr, GeneratedMarker) && !strings.Contains(contentStr, LegacyGeneratedMarker) {
		// 没有生成标记，说明是手动文件，不覆盖
		return &MergeResult{
			Content:  contentStr,
			Modified: false,
			Action:   "unchanged",
		}, nil
	}

	// 有生成标记，进行智能合并
	merged, err := mergeGeneratedFile(string(existingContent), newContent)
	if err != nil {
		return nil, err
	}

	isModified := merged != string(existingContent)
	action := "unchanged"
	if isModified {
		action = "updated"
	}

	return &MergeResult{
		Content:  merged,
		Modified: isModified,
		Action:   action,
	}, nil
}

// mergeGeneratedFile 合并生成的文件
// 保留手动添加的代码（在 ManualMarker 之后的部分）
func mergeGeneratedFile(existingContent, newContent string) (string, error) {
	// 查找手动代码部分
	manualCode := extractManualCode(existingContent)

	if manualCode == "" {
		// 没有手动代码，直接返回新内容
		return newContent, nil
	}

	// 在新内容中添加手动代码
	return appendManualCode(newContent, manualCode), nil
}

// extractManualCode 提取手动编写的代码
func extractManualCode(content string) string {
	lines := strings.Split(content, "\n")
	manualStart := -1

	for i, line := range lines {
		if strings.Contains(line, ManualMarker) {
			manualStart = i + 1
			break
		}
	}

	if manualStart == -1 || manualStart >= len(lines) {
		return ""
	}

	return strings.Join(lines[manualStart:], "\n")
}

// appendManualCode 将手动代码添加到生成的代码后
func appendManualCode(generatedContent, manualCode string) string {
	if manualCode == "" {
		return generatedContent
	}

	var buf bytes.Buffer
	buf.WriteString(generatedContent)

	// 确保有换行
	if !strings.HasSuffix(generatedContent, "\n") {
		buf.WriteString("\n")
	}

	buf.WriteString("\n")
	buf.WriteString(ManualMarker)
	buf.WriteString("\n")
	buf.WriteString(manualCode)

	return buf.String()
}

// MergeGoFile 智能合并 Go 文件（使用 AST）
// 支持更精细的函数级别合并
func MergeGoFile(filePath string, newContent string) (*MergeResult, error) {
	// 先尝试简单合并
	result, err := MergeFile(filePath, newContent)
	if err != nil || result.Action != "updated" {
		return result, err
	}

	// 如果是更新操作，尝试使用 AST 进行更精细的合并
	merged, err := mergeGoFileAST(filePath, newContent)
	if err != nil {
		// AST 合并失败，回退到简单合并
		return result, nil
	}

	return &MergeResult{
		Content:  merged,
		Modified: true,
		Action:   "updated",
	}, nil
}

// mergeGoFileAST 使用 AST 合并 Go 文件
func mergeGoFileAST(filePath string, newContent string) (string, error) {
	// 解析现有文件
	fset1 := token.NewFileSet()
	existingFile, err := parser.ParseFile(fset1, filePath, nil, parser.ParseComments)
	if err != nil {
		return "", err
	}

	// 解析新内容
	fset2 := token.NewFileSet()
	newFile, err := parser.ParseFile(fset2, "", newContent, parser.ParseComments)
	if err != nil {
		return "", err
	}

	// 提取现有文件中的手动函数（没有生成标记的）
	manualFuncs := extractManualFunctions(existingFile)

	// 将手动函数添加到新文件
	for _, fn := range manualFuncs {
		newFile.Decls = append(newFile.Decls, fn)
	}

	// 格式化输出
	var buf bytes.Buffer
	if err := format.Node(&buf, fset2, newFile); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// extractManualFunctions 提取手动编写的函数
func extractManualFunctions(file *ast.File) []ast.Decl {
	var manualFuncs []ast.Decl

	for _, decl := range file.Decls {
		funcDecl, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}

		// 检查函数注释中是否有生成标记
		if funcDecl.Doc != nil {
			hasGeneratedMarker := false
			for _, comment := range funcDecl.Doc.List {
				if strings.Contains(comment.Text, "Code generated") {
					hasGeneratedMarker = true
					break
				}
			}
			if !hasGeneratedMarker {
				// 没有生成标记，说明是手动函数
				manualFuncs = append(manualFuncs, funcDecl)
			}
		} else {
			// 没有注释的函数视为手动函数
			manualFuncs = append(manualFuncs, funcDecl)
		}
	}

	return manualFuncs
}

// WriteFile 写入文件（带合并逻辑）
func WriteFile(filePath string, content string, useAST bool) error {
	var result *MergeResult
	var err error

	if useAST && strings.HasSuffix(filePath, ".go") {
		result, err = MergeGoFile(filePath, content)
	} else {
		result, err = MergeFile(filePath, content)
	}

	if err != nil {
		return err
	}

	// 格式化 Go 代码
	finalContent := result.Content
	if strings.HasSuffix(filePath, ".go") {
		formatted, err := formatGoCode(finalContent)
		if err == nil {
			finalContent = formatted
		}
		// 格式化失败时继续使用原内容
	}

	// 写入文件
	if err := os.WriteFile(filePath, []byte(finalContent), 0644); err != nil {
		return err
	}

	// 打印操作信息
	switch result.Action {
	case "created":
		fmt.Printf("✅ Created %s\n", filePath)
	case "updated":
		fmt.Printf("🔄 Updated %s\n", filePath)
	case "unchanged":
		fmt.Printf("⏭️  Skipped %s (manual file)\n", filePath)
	}

	return nil
}

// formatGoCode 格式化 Go 代码
func formatGoCode(source string) (string, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, "", source, parser.ParseComments)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := format.Node(&buf, fset, node); err != nil {
		return "", err
	}

	return buf.String(), nil
}
