// Code generated by scene-script-cli. DO NOT EDIT.

package script_chapter

import (
	"github.com/gin-gonic/gin"

	"scene-script/internal/logic/script_chapter"
	"scene-script/internal/svc"
	"scene-script/internal/types"
	"scene-script/pkg/httpn"
)

// CreateScriptChapterHandler 创建
func CreateScriptChapterHandler(svc *svc.ServiceContext) gin.HandlerFunc {
	return func(c *gin.Context) {
		var req types.CreateScriptChapterReq
		if err := httpn.BindJSON(c, &req); err != nil {
			httpn.Error(c, err)
			return
		}

		l := script_chapter.NewCreateScriptChapterLogic(c.Request.Context(), svc)
		resp, err := l.CreateScriptChapter(&req)
		if err != nil {
			httpn.HandleError(c, err)
			return
		}

		httpn.Ok(c, resp)
	}
}
