// Code generated by scene-script-cli. DO NOT EDIT.

package script_chapter

import (
	"github.com/gin-gonic/gin"

	"scene-script/internal/logic/script_chapter"
	"scene-script/internal/svc"
	"scene-script/pkg/httpn"
)

// DeleteScriptChapterHandler 删除
func DeleteScriptChapterHandler(svc *svc.ServiceContext) gin.HandlerFunc {
	return func(c *gin.Context) {
		id, err := httpn.PathInt64(c, "id")
		if err != nil {
			httpn.BadRequest(c, "无效的ID")
			return
		}

		l := script_chapter.NewDeleteScriptChapterLogic(c.Request.Context(), svc)
		err = l.DeleteScriptChapter(id)
		if err != nil {
			httpn.HandleError(c, err)
			return
		}

		httpn.Ok(c, nil)
	}
}
